$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Split-Path $PSScriptRoot -Parent;$env:DP_SKIP_START='1';. (Join-Path $root 'Conformance\Calculator.ps1')
$button=$script:Buttons[4];$state=[CalculatorState]::new();$callable=Get-Command Invoke-CalculatorLogic -CommandType Function
$objects=@(
    [pscustomobject]@{ObjectId=104;SemanticType='Calculator.Button';Origin='SMA-created application object';Classification='OBJECT-REPRESENTABLE';References=@(2,10004);Facts=[ordered]@{Label=$button.Label;Kind=$button.Type;GridX=$button.GridX;GridY=$button.GridY}},
    [pscustomobject]@{ObjectId=2;SemanticType='Calculator.State';Origin='SMA-created application object';Classification='OBJECT-REPRESENTABLE';References=@();Facts=[ordered]@{DisplayValue=$state.DisplayValue}},
    [pscustomobject]@{ObjectId=10004;SemanticType='Calculator.HostedCapability';Origin='Projection capability binding';Classification='HOSTED';References=@(10005,2);Facts=[ordered]@{Operation='InvokeButton';TargetObjectId=104;CallableName=$callable.Name}},
    [pscustomobject]@{ObjectId=10005;SemanticType='SMA.FunctionInfo';Origin='Authentic SMA command object';Classification='OBJECT-REPRESENTABLE';References=@(10006);Facts=[ordered]@{Name=$callable.Name;Parameters=@($callable.Parameters.Keys);CommandType=[string]$callable.CommandType;Source=$callable.Source}},
    [pscustomobject]@{ObjectId=10006;SemanticType='SMA.ScriptBlock';Origin='Authentic SMA callable object';Classification='HOSTED/OPAQUE';References=@(10007);Facts=[ordered]@{File=$callable.ScriptBlock.File;ScriptBlockId=[string]$callable.ScriptBlock.Id;IsFilter=$callable.ScriptBlock.IsFilter;Module=if($callable.ScriptBlock.Module){$callable.ScriptBlock.Module.Name}else{$null}}},
    [pscustomobject]@{ObjectId=10007;SemanticType='SMA.SessionState';Origin='Hosted execution environment';Classification='SEMANTIC GAP';References=@();Facts=[ordered]@{Reason='FunctionInfo invocation requires hosted PowerShell command/session semantics; no public object-level executable semantic representation was observed.'}}
)
$receipt=[pscustomobject][ordered]@{test='Button 104 authentic SMA capability census';pass=$true;source='unchanged Calculator.ps1 loaded by PowerShell';objects=$objects;objectCount=$objects.Count;objectReferenceEdges=(@($objects|ForEach-Object{$_.References}).Count);classifications=($objects|Group-Object Classification|ForEach-Object{"$($_.Name)=$($_.Count)"});proven='Button, state, FunctionInfo, and ScriptBlock identities are observable as live objects.';hosted='ScriptBlock and SessionState remain hosted.';detached='NONE';semanticGap='SMA exposes the callable object but not a public object-level executable semantic population sufficient to invoke it after hosted PowerShell termination.';verdict='PASS: census completed; DETACHMENT NOT PROVEN'}
$receipt
